on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.5"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter build apk --release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}      


          
# on: 
#   push:
#     tags:
#     - '*'

# name: "Telegram Post"

# jobs:
#   notifyTelegram:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Telegram<apk>
#       uses: appleboy/telegram-action@master
#       with:
#         to: ${{ secrets.TELEGRAM_TO }}
#         token: ${{ secrets.TELEGRAM_TOKEN }}
#         document: build/app/outputs/flutter-apk/*.apk

# name: Releases

# on: 
#   push:
#     tags:
#     - '*'

# jobs:

#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#     - uses: actions/checkout@v2
#     - uses: ncipollo/release-action@v1
#       with:
#         artifacts: "release.tar.gz,foo/*.txt"
#         bodyFile: "body.md"
#         token: ${{ secrets.GITHUB_TOKEN }}